<Project>
	<Import Project="./Universal.targets" />

	<Target
		Name="Copy"
		AfterTargets="Build"
	>
    <ItemGroup>
      <Files Include="$(OutputPath)*.dll" />
    </ItemGroup>
		<MakeDir Directories="./mod/$(MOD)"/>
		<Copy SourceFiles="manifest.json" DestinationFOlder="./mod/$(MOD)"/>
		<Copy SourceFiles="$(OutputPath)/$(MOD).dll" DestinationFolder="./mod/$(MOD)"/>
		<Copy SourceFiles="$(OutputPath)/Common.dll" DestinationFolder="./mod/$(MOD)" Condition="Exists('$(OutputPath)/Common.dll')"/>
	</Target>

	<Target
		Name="Restart"
		AfterTargets="Copy"
		Condition="'$(RESTART)' == 'true' and ('$(DOTNET_WATCH_ITERATION)' == '' or $(DOTNET_WATCH_ITERATION) > 1)"
	>
		<Message Text="trying to restart timberborn" Importance="High" />
		    <Exec Command="zsh ../tool restart"/>
	</Target>
</Project>
